[{if in_array($sPaymentID, array('novalnetcreditcard', 'novalnetsepa', 'novalnetinvoice', 'novalnetprepayment', 'novalnetonlinetransfer', 'novalnetideal', 'novalnetpaypal', 'novalneteps', 'novalnetgiropay', 'novalnetprzelewy24','novalnetbarzahlen'))}]
    [{assign var="oConf" value=$oViewConf->getConfig()}]
    [{assign var="sPaymentHomePageUrl" value=$sPaymentID|cat:"_url"}]
    [{assign var="sGetActiveTheme" value=$oViewConf->getActiveTheme()}]
    [{if $sPaymentID == "novalnetcreditcard"}]
		[{assign var="sTemplatePath" value=$sGetActiveTheme|cat:'/novalnetcreditcard.tpl'}]
		[{include file=$oView->getPaymentTemplatePath($sTemplatePath)}]
	[{elseif $sPaymentID == "novalnetsepa"}]
		[{assign var="sTemplatePath" value=$sGetActiveTheme|cat:'/novalnetsepa.tpl'}]
		[{include file=$oView->getPaymentTemplatePath($sTemplatePath)}]
	[{elseif $sPaymentID == "novalnetinvoice"}]
		[{assign var="sTemplatePath" value=$sGetActiveTheme|cat:'/novalnetinvoice.tpl'}]
		[{include file=$oView->getPaymentTemplatePath($sTemplatePath)}]
	[{elseif $sPaymentID == "novalnetpaypal"}]
		[{assign var="sTemplatePath" value=$sGetActiveTheme|cat:'/novalnetpaypal.tpl'}]
		[{include file=$oView->getPaymentTemplatePath($sTemplatePath)}]
	[{elseif in_array($sPaymentID, array("novalnetprepayment", "novalnetbarzahlen"))}]
		[{assign var="sTemplatePath" value=$sGetActiveTheme|cat:'/novalnetdirect.tpl'}]
		[{include file=$oView->getPaymentTemplatePath($sTemplatePath)}]
	[{elseif in_array($sPaymentID, array("novalnetonlinetransfer", "novalnetideal", "novalneteps", "novalnetgiropay", "novalnetprzelewy24"))}]		
		[{assign var="sTemplatePath" value=$sGetActiveTheme|cat:'/novalnetredirect.tpl'}]
		[{include file=$oView->getPaymentTemplatePath($sTemplatePath)}]
	[{/if}]            
[{else}]
    [{$smarty.block.parent}]
[{/if}]
